"""Contract for generic (any-schema) site adapters.

Parallels classifieds/sites/base.py, but deliberately decoupled from car
semantics: a generic adapter yields plain record dicts (not classifieds.Listing)
so it can scrape any shape of data. Adapters are generated by aiconfig.generate
for sites that selector-config can't handle (anti-bot, login walls, bespoke JS),
and only run after their module is reviewed + merged to main.

An adapter module (adapters/<key>.py) must expose a top-level `ADAPTER` instance
(or a `build()` factory) implementing this Protocol, plus pure
`parse_search_html` / `parse_detail_html` functions so it's testable off captured
fixtures with no network.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterator, Protocol


@dataclass
class FetchSpec:
    """What the generic source asked for. Built from a /generic_sources doc."""
    start_urls: list[str] = field(default_factory=list)
    record_schema: list[dict] = field(default_factory=list)  # [{name,type,required}]
    max_records: int = 50
    query: str = ""
    country: str = ""
    city: str = ""
    notes: str = ""

    @classmethod
    def from_source(cls, source: dict) -> "FetchSpec":
        return cls(
            start_urls=list(source.get("start_urls") or []),
            record_schema=list(source.get("record_schema") or []),
            max_records=int(source.get("max_records") or 50),
            query=str(source.get("query") or ""),
            country=str(source.get("country") or ""),
            city=str(source.get("city") or ""),
            notes=str(source.get("notes") or ""),
        )

    def required_fields(self) -> list[str]:
        return [
            str(f.get("name"))
            for f in self.record_schema
            if isinstance(f, dict) and f.get("required") and f.get("name")
        ]


class Adapter(Protocol):
    key: str            # registry name (module stem), e.g. "acme_grants"
    label: str          # human name

    def fetch(self, spec: FetchSpec) -> Iterator[dict]:
        """Yield records. Each record is a dict with a "url" key and a "data"
        dict of the extracted fields (matching the source's record_schema)."""
        ...


def read_fixture(name: str) -> str:
    """Read a captured HTML fixture from tests/fixtures/generic/ by BASENAME.

    Generated adapter tests use this instead of `open`/`pathlib` so they can be
    run through the strict AST safety gate (which denies file/path primitives) —
    a test can read its own fixtures but nothing else. Path components in `name`
    are stripped, so it can never traverse out of the fixtures directory.
    """
    import os

    base = os.path.basename(str(name))
    path = os.path.join(os.getcwd(), "tests", "fixtures", "generic", base)
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()
